### ISSUE TITLE
Use BLAKE-3 instead of SHA or BLAKE-2b

### ISSUE THREAD

**Issue by yonas** [jedisct1/rust-minisign#28]
[BLAKE-3](https://github.com/BLAKE3-team/BLAKE3) is 10-15x faster than SHA family of hashes, and 7x faster than BLAKE-2b.

> The [blake3](https://crates.io/crates/blake3) Rust crate, which includes optimized implementations for SSE2, SSE4.1, AVX2, AVX-512, and NEON, with automatic runtime CPU feature detection on x86. The rayon feature provides multithreading.

![alt text](https://github.com/BLAKE3-team/BLAKE3/blob/master/media/speed.svg?raw=true)

**Comment by yonas** [comment]
## Suggestions

- move the existing blake2b and sha code into non-default features
- add blake3 as a default feature
- add a version header tag for backwards compatibility.

**Comment by jedisct1** [comment]
No.

**Comment by jedisct1** [comment]
Minisign is not a Rust app.

It's been around and stable since 2015, has a specification, and multiple implementations that must be interoperable. The one in Rust has nothing special.

Efficiency is dominated by the signature itself, not the hashing algorithm. And there's nothing wrong with BLAKE2, which is more commonly available and has a higher security margin than BLAKE3.  Such change would fragment the ecosystem without providing any value. Post-quantum signatures would be a better justification for extending the specification. 

Not sure where you saw SHA-3 being used here.
